substitutions:
  name: esp32-bluetooth-proxy
  friendly_name: Bluetooth Proxy
packages:
  esphome.bluetooth-proxy: github://r3mcos3/esphome-nodes/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
