esphome:
  name: multi-node

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Multi-Node Fallback Hotspot"
    password: !secret hotspot_password

captive_portal:

esp32_ble_tracker:

sensor:
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:5C:AA:5B"
    temperature:
      name: "Sensor1 Temperature"
    humidity:
      name: "Sensor1 Humidity"
    battery_level:
      name: "Sensor1 Battery-Level"
    battery_voltage:
      name: "Sensor1 Battery-Voltage"
    signal_strength:
      name: "Sensor1 Signal"
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:F0:AC:5B"
    temperature:
      name: "Sensor2 Temperature"
    humidity:
      name: "Sensor2 Humidity"
    battery_level:
      name: "Sensor2 Battery-Level"
    battery_voltage:
      name: "Sensor2 Battery-Voltage"
    signal_strength:
      name: "Sensor3 Signal"
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:FB:E5:F7"
    temperature:
      name: "Sensor3 Temperature"
    humidity:
      name: "Sensor3 Humidity"
    battery_level:
      name: "Sensor3 Battery-Level"
    battery_voltage:
      name: "Sensor3 Battery-Voltage"
    signal_strength:
      name: "Sensor3 Signal"
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:3E:E2:26"
    temperature:
      name: "Sensor4 Temperature"
    humidity:
      name: "Sensor4 Humidity"
    battery_level:
      name: "Sensor4 Battery-Level"
    battery_voltage:
      name: "Sensor4 Battery-Voltage"
    signal_strength:
      name: "Sensor4 Signal"
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:9A:3D:03"
    temperature:
      name: "Sensor5 Temperature"
    humidity:
      name: "Sensor5 Humidity"
    battery_level:
      name: "Sensor5 Battery-Level"
    battery_voltage:
      name: "Sensor5 Battery-Voltage"
    signal_strength:
      name: "Sensor5 Signal"
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:08:69:41"
    temperature:
      name: "Sensor6 Temperature"
    humidity:
      name: "Sensor6 Humidity"
    battery_level:
      name: "Sensor6 Battery-Level"
    battery_voltage:
      name: "Sensor6 Battery-Voltage"
    signal_strength:
      name: "Sensor6 Signal"
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:E4:B0:33"
    temperature:
      name: "Sensor7 Temperature"
    humidity:
      name: "Sensor7 Humidity"
    battery_level:
      name: "Sensor7 Battery-Level"
    battery_voltage:
      name: "Sensor7 Battery-Voltage"
    signal_strength:
      name: "Sensor7 Signal"