substitutions:
  name: rolluik-voor
  friendly_name: Rolluik Voor
packages: github://r3mcos3/esphome-nodes/rolluik.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password