substitutions:
  name: rolluik
  friendly_name: Rolluik
  open_time: 35s
  close_time: 35s

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: esphome.rolluik
    version: "1.0"

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: ${name}
    password: !secret hotspot_password

api:
captive_portal:
web_server:
  port: 80

dashboard_import:
  package_import_url: github://r3mcos3/esphome-nodes/rolluik.yaml@main

binary_sensor:
  - platform: gpio
    pin: GPIO10
    id: but_case
    on_press:
      then:
        - cover.toggle: my_cover

button:
  - platform: restart
    name: "${friendly_name} Restart"

switch:
- platform: gpio
  pin: GPIO12
  interlock: &interlock [open_cover, close_cover]
  id: open_cover
- platform: gpio
  pin: GPIO5
  interlock: *interlock
  id: close_cover
- platform: gpio
  pin: GPIO13
  name: "${friendly_name} LED"
  inverted: true

cover:
- platform: time_based
  name: "${friendly_name}"
  id: my_cover
  open_action:
    - switch.turn_on: open_cover
  open_duration: ${open_time}
  close_action:
    - switch.turn_on: close_cover
  close_duration: ${close_time}
  stop_action:
    - switch.turn_off: open_cover
    - switch.turn_off: close_cover