substitutions:
  name: roller-shutter-upstairs
  friendly_name: Roller Shutter Upstairs

esphome:
  name: ${name}

esp8266:
  board: esp01_1m

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api: 

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  min_auth_mode: WPA2
  manual_ip:
    static_ip: 10.10.2.195
    gateway: 10.10.2.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret hotspot_password
    ap_timeout: 1min

captive_portal:

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "${friendly_name} Uptime"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${friendly_name} IP Address"
    ssid:
      name: "${friendly_name} SSID"
    bssid:
      name: "${friendly_name} BSSID"
  - platform: version
    name: "${friendly_name} ESPHome Version"

binary_sensor:
  - platform: gpio
    pin: GPIO10
    id: but_case
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    on_press:
      then:
        - cover.toggle: my_cover

button:
  - platform: restart
    name: "${friendly_name} Restart"

switch:
- platform: gpio
  pin: GPIO12
  interlock: &interlock [open_cover, close_cover]
  id: open_cover
- platform: gpio
  pin: GPIO5
  interlock: *interlock
  id: close_cover
- platform: gpio
  pin: GPIO13
  name: "${friendly_name} LED"
  inverted: true

cover:
- platform: time_based
  name: "${friendly_name}"
  id: my_cover
  open_action:
    - switch.turn_on: open_cover
  open_duration: 25s
  close_action:
    - switch.turn_on: close_cover
  close_duration: 21s
  stop_action:
    - switch.turn_off: open_cover
    - switch.turn_off: close_cover
