substitutions:
  name: wasmachine
  friendly_name: Wasmachine

esphome:
  name: wasmachine

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:


ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Wasmachine Fallback Hotspot"
    password: !secret hotspot_password

captive_portal:

web_server:
  port: 80

button:
  - platform: restart
    name: "${friendly_name} Restart"

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    current:
      name: "${friendly_name} Current"
    voltage:
      name: "${friendly_name} Voltage"
    power:
      name: "${friendly_name} Power"
    energy:
      name: "${friendly_name} Energy"