---
substitutions:
  name: pow_r2
  friendly_name: Sonoff Pow R2

dashboard_import:
  package_import_url: github://r3mcos3/esphome-nodes/pow_r2/pow_r2.yaml@main

esphome:
  name: ${name}
  platform: esp8266
  board: esp1_1m
  name_add_mac_suffix: true
  project:
    name: r3mcos3.pow_r2
    version: "1.0"

wifi:
  ssid: # Enter your WiFi SSID here. Example: `ssid: 'your_network_name'`
  password: # Enter your wifi password here. Example: `password: 'abcde123456'`
  ap:
    ssid: "${friendly_name}_fallback_hotspot"
    password: "${friendly_name}_1234"

# Enable logging
logger:

# Enable Home Assistant API
api:

captive_portal:

web_server:
  port: 80

button:
  - platform: restart
    name: "${friendly_name} Restart"

uart:
  rx_pin: RX
  baud_rate: 4800

sensor:
  - platform: cse7766
    current:
      name: "${friendly_name} Current"
    voltage:
      name: "${friendly_name} Voltage"
    power:
      name: "${friendly_name} Power"
    energy:
      name: "${friendly_name} Energy"
